language: c
sudo: required
warnings_are_errors: true

branches:
  except:
    - example-data
    - gh-pages

before_install:
  - curl -OL https://raw.githubusercontent.com/bleutner/r-builder/install_version/pkg-build.sh
  #- curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
  - chmod 755 pkg-build.sh
  - ./pkg-build.sh bootstrap

before_script:
  - sudo apt-get install aptitude -y
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -qq
  - sudo aptitude install -y gdal-bin
  - sudo aptitude install -y libgdal1-dev
  - sudo aptitude install -y libproj-dev
  - wget https://github.com/bleutner/withr/blob/master/withr_1.0.0.9000.tar.gz?raw=true
  - ./pkg-build.sh install_r_local "withr_1.0.0.9000.tar.gz"
  - rm withr_1.0.0.9000.tar.gz 
  - ./pkg-build.sh install_devtools 
  - ./pkg-build.sh install_r_version car 2.0-25 
  - ./pkg-build.sh install_deps
# Run twice, just to be sure because sometimes cran mirror fails randomly 
  - ./pkg-build.sh install_deps

script: 
  - ./pkg-build.sh run_build
  - ./pkg-build.sh run_check

after_failure:
  - ./pkg-build.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

env:
  matrix:
    - RVERSION=oldrel
    - RVERSION=release
    - RVERSION=devel

